name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bundle application
        run: |
          cat src/core/*.js src/learning/*.js src/ui/*.js > docs/app.js
          echo "// Bundle created: $(date)" >> docs/app.js

      - name: Copy data files
        run: |
          mkdir -p docs/data
          cp -r data/specs docs/data/
          cp data/manifest.json docs/data/
          cp data/schema.json docs/data/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs